version: '3.8'

services:
  downloader:
    build: .
    container_name: telegram-downloader-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME:-downloader_bot}
      - YTDLP_MODE=http
      - YTDLP_SERVICE_URL=http://ytdlp-service:8090
      - DOWNLOAD_DIR=/app/downloads
      - CACHE_TTL_HOURS=24
      - SIZE_LIMIT_MB=50
    volumes:
      # Внешнее файловое хранилище для загруженных файлов
      - ./downloads:/app/downloads
      # Можно также использовать именованный том:
      # - downloads:/app/downloads
    depends_on:
      ytdlp-service:
        condition: service_healthy
    restart: unless-stopped

  ytdlp-service:
    build:
      context: ./ytdlp-service
      dockerfile: Dockerfile
    container_name: ytdlp-service
    volumes:
      # Общая директория с основным сервисом для загруженных файлов
      - ./downloads:/downloads
    environment:
      - DOWNLOAD_DIR=/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  # Именованный том для загрузок (можно использовать вместо ./downloads)
  downloads:
