version: '3.8'

services:
  downloader:
    build: .
    container_name: telegram-downloader-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME:-downloader_bot}
      - YTDLP_BIN=/usr/local/bin/yt-dlp
      - DOWNLOAD_DIR=/app/downloads
      - CACHE_TTL_HOURS=24
      - SIZE_LIMIT_MB=50
    volumes:
      # Внешнее файловое хранилище для загруженных файлов
      - ./downloads:/app/downloads
      # Можно также использовать именованный том:
      # - downloads:/app/downloads
    depends_on:
      - ytdlp
    restart: unless-stopped

  ytdlp:
    build:
      context: .
      dockerfile: Dockerfile.ytdlp
    container_name: ytdlp-service
    volumes:
      # Общая директория с основным сервисом для загруженных файлов
      - ./downloads:/downloads
    command: ["--version"]
    restart: "no"

volumes:
  # Именованный том для загрузок (можно использовать вместо ./downloads)
  downloads:
